version: "3.5"

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    restart: always
  server:
    build: .
    ports:
      - "3000:3000"
    restart: always
