version: "3.5"

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    restart: always
  server:
    image: superj80820/2020-dcard-homework
    environment:
      - RESTFULHOST=0.0.0.0
      - RESTFULPORT=3000
      - REDISADDRESS=redis:6379
    ports:
      - "3000:3000"
    restart: always
