apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yaml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yaml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: REDISADDRESS
              value: redis:6379
            - name: RESTFULHOST
              value: 0.0.0.0
            - name: RESTFULPORT
              value: "3000"
          image: superj80820/2020-dcard-homework
          name: server
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
